/**
 * DocAgent - Auto-documentation Agent
 * Documents everything automatically, creates summaries
 */

const fs = require('fs');
const path = require('path');

class DocAgent {
  constructor(workspacePath = '/home/ubuntu/.openclaw/workspace') {
    this.workspace = workspacePath;
    this.docsDir = path.join(workspacePath, 'docs');
  }

  // ============================================
  // AUTO-DOCUMENT
  // ============================================

  /**
   * Document project state
   */
  documentProject(name, status) {
    const file = path.join(this.docsDir, `project-${name}.md`);
    
    const content = `# ${name}

Status: ${status.status}
Last Updated: ${new Date().toISOString()}

## Details
${JSON.stringify(status, null, 2)}

---
Auto-generated by DocAgent
`;
    
    fs.writeFileSync(file, content);
    return `📝 Documented: ${name}`;
  }

  /**
   * Create system summary
   */
  createSystemSummary(systems) {
    const file = path.join(this.docsDir, 'system-summary.md');
    
    let content = `# DHEEB System Summary
Generated: ${new Date().toISOString()}

## Systems
`;
    
    for (const [name, status] of Object.entries(systems)) {
      content += `\n### ${name}\n`;
      content += `- Status: ${status}\n`;
    }
    
    fs.writeFileSync(file, content);
    return '✅ System summary created';
  }

  /**
   * Log action
   */
  log(action, details) {
    const file = path.join(this.docsDir, 'action-log.md');
    const entry = `\n- **${new Date().toISOString()}**: ${action} - ${JSON.stringify(details)}`;
    
    fs.appendFileSync(file, entry);
  }

  // ============================================
  // GENERATE REPORTS
  // ============================================

  /**
   * Generate daily report
   */
  generateDailyReport(data) {
    const file = path.join(this.docsDir, `daily-${new Date().toISOString().split('T')[0]}.md`);
    
    const content = `# Daily Report - ${new Date().toISOString().split('T')[0]}

## Summary
${data.summary || 'No summary'}

## Tasks Completed
${data.completed?.map(t => `- ${t}`).join('\n') || 'None'}

## Issues
${data.issues?.map(i => `- ${i}`).join('\n') || 'None'}

## Next Steps
${data.nextSteps?.map(n => `- ${n}`).join('\n') || 'None'}
`;
    
    fs.writeFileSync(file, content);
    return `📊 Daily report: ${file}`;
  }
}

module.exports = DocAgent;
